### ISSUE TITLE
Mid-semester check in

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [DukeStatSci/thesis-sp18-driscoll-envjustice#4]
@amd112 Please respond to the following questions in a reply to this issue by Wednesday Oct 18, 5pm. Brief answers are ok.

1. What is the ultimate goal of the thesis?
2. What portion of the thesis work have you completed so far?
3. What parts of the analysis do you plan on completing by the end of the semester?
4. What sections do you expect to include in your Fall semester write up? (Note that this is due as a gitbook and PDF output on Dec 7 at 9am, I'll take a snapshot of your repo at that time.)

**Comment by amd112** [comment]
1) Ultimate goal of the thesis is to examine how toxicity burden has changed over time for several minority groups in America. Stretch goal would be to be able to find a defensible to munge my data (SAE? IPF? Extrapolating between census years?) so that I could get find enough detail that I could make more statements about the issue that take in to account the crucial intersectional aspect of the question (as briefly discussed in the section on census data and the level of analysis section)

2) I've created a package (see the github repo called rseiAnalysis) that has bite sized parts of the simulation code I'm planning on using. I've written parts of the Report, amounting to about 12 pages of text and figures. 

3) My biggest challenge for this semester is (see above) finding a way, within the constraints of the data I'm using to be able to simulate the question of interest in a fine grain enough way. Can I extrapolate decennial census data to examine an incredibly interesting time in environmental justice (~1990) or should I focus on recent developments, since I have the ACS available? Can I model crosstabs at lower levels of census geography? Can I create my own crosstabs of the 1990 geographies so that I can have comparable tracts over time? 

4) I expect to put together a preliminary introduction to Environmental Justice, a moderately in depth discussion of my data and the various limitations it has, a discussion on the design choices that I'm having to make within the constraints of the data, and a preliminary discussion of results I have at the time.

**Comment by amd112** [comment]
Leaving open in case you have more questions!
